### PR TITLE
Add AES-128 library

### PR DESCRIPTION
**Pull request by SevenW**

### CODE REVIEW

**Comment by SevenW** [comment]
First attempt to add a doc file. Can I have one doc file referring to three source files?

**Comment by jcw** [comment]
W o w - many thanks!

**Comment by jcw** [comment]
Unfortunately not, the current doc setup is too limited for that - we can either split the docs or merge the code (splitting seems more practical, given the amount of code dragged in).

**Comment by jcw** [comment]
I've resolved it by merging aes-ctr-cmac into aes and documenting aes-inv separately.

**Pull request merged**
