### PR TITLE
Wait for RFM69 interrupt

### PR DESCRIPTION
**Pull request by JohnOH**
Hold fire on this. I have upset the GPIO setup code.

### CODE REVIEW

**Comment by jcw** [comment]
Is it really this simple? No problems with race conditions, etc? Wow.

**Comment by JohnOH** [comment]
That is a good question. I guess that once the FIFO is empty we are re-armed for the next interrupt and if it fires before we begin waiting for it then it will freeze. You can use a timeout in WFI but that feels like cheating.

**Comment by JohnOH** [comment]
Pah, I have looked into the wiringPi library and I now think that waitForInterrupt simply does its own loop waiting for the pin to be set - nett zero gain. I will look further into wiringPiISR which appears closer to what we are looking for but just not so easy. We also need a way to suspend our process and wait for the interrupt - without looping.

**Comment by JohnOH** [comment]
Interesting how increasing the task priority impairs performance.

**Comment by JohnOH** [comment]
Adjusting process priority before interrupt service routine is setup causes problems when packets start to arrive. Perhaps the ISR inherits its priority from the main routine.

**Pull request closed without merging**
