### PR TITLE
Merge `pid.fs`, `timed.fs` and SolderIronController into master

### PR DESCRIPTION
**Pull request by tht**
I've moved the libraries in `flib/any` as discussed. The SolderIronController is *work in progress*, the two libraries are working just fine but need more testing.

### CODE REVIEW

**Comment by jcw** [comment]
Oooh, many thanks!

**Comment by jcw** [comment]
I've also deleted the branch, but feel free to re-create as needed.

**Comment by tht** [comment]
I still have some other stuff in there and need the branch for reference to to a final merge. I've restored it for now and will delete it myself as soon as this is done.

**Comment by jcw** [comment]
Ok. Minor tweaks, and now your new docs are also [online](http://embello.jeelabs.org/flib/).

**Comment by tht** [comment]
Looks good, thank you!

**Pull request merged**
